Squashed commit of the following:
commit 5c0fdfde2512baed8a37bde8c50c4bce649930b3
Author: Mason Remy <masonr@microsoft.com>
Date:   Wed Jun 1 20:17:00 2022 +0000

    Merged PR 2599: Support parameterizing caches based on memory space

    Support parameterizing caches based on memory space

    - Identifies bound indices that the cache should be parameterized on,
      rather than shaped by.
      e.g. for a private memory cache inserted at a gpu block level, the
      computed memory space will not be the full active block at that level,
      but the portion derived from loops that weren't bound to gpu thread
      dims.

    - Adds some BoundProcessorOp utilities and shares some common binding
      code

commit 2c4cceca16084554b4af458525fc68f06503bea1
Author: Ritwik Das <ritdas@microsoft.com>
Date:   Wed Jun 1 08:46:52 2022 +0000

    Merged PR 2618: Fix memory allocation bug during benchmark verification

    Fix memory allocation bug during benchmark  verification

commit 2977b3b905109d2405524d7e6eb1583eed9f2d7d
Author: Lisa Ong <onglisa@microsoft.com>
Date:   Wed Jun 1 04:19:38 2022 +0000

    Merged PR 2617: [nfc] [doc] Fix typo and re-sync models table

commit 53dfbdb0e42250cf877da0c0e04f93acedc5caf4
Author: Denny Sun <dennys@microsoft.com>
Date:   Wed Jun 1 03:38:27 2022 +0000

    Merged PR 2616: Formatting Python code a bit for the better readability

    1. Some functions have a long list of parameters, add line wrap
    2. Separate external imports from internal ones

commit 92565fa4495e828efb698078e30a5233d343f287
Author: Ritwik Das <ritdas@microsoft.com>
Date:   Tue May 31 07:41:56 2022 +0000

    Merged PR 2614: Remove redundant variable and cosmosdb fix

    Cosmos DB error when upserting from multiple processes:

    Process runner0:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
        self.run()
      File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
        self._target(*self._args, **self._kwargs)
      File "/azp/_work/2/s/tools/benchmarkers/accera_gemm.py", line 633, in gemm_runner
        cosmosdb.upsert_benchmark_results(resultRows, containerName, verboseLogs)
      File "/azp/_work/2/s/tools/benchmarkers/cosmosdb.py", line 27, in upsert_benchmark_results
        container = get_container(containerName, verboseLogs)
      File "/azp/_work/2/s/tools/benchmarkers/cosmosdb.py", line 18, in get_container
        container = db.create_container_if_not_exists(id=containerName, partition_key=PartitionKey(path='/partitionKey'))
      File "/usr/local/lib/python3.8/dist-packages/azure/core/tracing/decorator.py", line 62, in wrapper_use_tracer
        return func(*args, **kwargs) # type: ignore
      File "/usr/local/lib/python3.8/dist-packages/azure/cosmos/database.py", line 287, in create_container_if_not_exists
        container_proxy.read(
      File "/usr/local/lib/python3.8/dist-packages/azure/core/tracing/decorator.py", line 62, in wrapper_use_tracer
        return func(*args, **kwargs) # type: ignore
      File "/usr/local/lib/python3.8/dist-packages/azure/cosmos/container.py", line 145, in read
        self._properties = self.client_connection.ReadContainer(
      File "/usr/local/lib/python3.8/dist-packages/azure/cosmos/_cosmos_client_connection.py", line 469, in ReadContainer
        return self.Read(path, "colls", collection_id, None, options, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/azure/cosmos/_cosmos_client_connection.py", line 2162, in Read
        result, self.last_response_headers = self.__Get(path, request_params, headers, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/azure/cosmos/_cosmos_client_connection.py", line 2209, in __Get
        return synchronized_request.SynchronizedRequest(
      File "/usr/local/lib/python3.8/dist-packages/azure/cosmos/_synchronized_request.py", line 210, in SynchronizedRequest
        return _retry_utility.Execute(
      File "/usr/local/lib/python3.8/dist-packages/azure/cosmos/_retry_utility.py", line 73, in Execute
        result = ExecuteFunction(function, global_endpoint_manager, *args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/azure/cosmos/_retry_utility.py", line 130, in ExecuteFunction
        return function(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/azure/cosmos/_synchronized_request.py", line 158, in _Request
        raise exceptions.CosmosHttpResponseError(message=data, response=response)
    azure.cosmos.exceptions.CosmosHttpResponseError: Status code: 400
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
    <HTML><HEAD><TITLE>Bad Request</TITLE>
    <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
    <BODY><h2>Bad Request</h2>
    <hr><p>HTTP Erro...

commit 34fadcd529161a656a34f67288fb934b42a73524
Author: Ritwik Das <ritdas@microsoft.com>
Date:   Tue May 31 00:37:59 2022 +0000

    Merged PR 2613: Enable daily CUDA benchmarks

    - Enable CUDA benchmarks
    - some refactoring

commit 52d7f77ecea2d437f658be9cf898724ee220e670
Author: Mason Remy <masonr@microsoft.com>
Date:   Mon May 30 05:57:31 2022 +0000

    Merged PR 2596: Updates to affine simplifications

    Updates to affine simplifications

    - Run simplifications on AffineApplyOps
    - Detect and simplify some single-element-numerator cases for floordiv
      and mod
    - Detect GPU constants such grid dim size and block dim size and
      incorporate those constants into affine maps for later simplification
    - Detect GPU bound dimensions block id and thread id in affine ops and
      incorporate those ranges into simplification passes

    Related work items: #3667

commit 2e1b837854692a64df920b7b3ef44d9d5a5ca3fa
Author: Mason Remy <masonr@microsoft.com>
Date:   Fri May 27 22:02:47 2022 +0000

    Merged PR 2594: Always resolve unrealized loopnest indices when computing cache positions

    Always resolve unrealized loopnest indices when
    computing cache positions

commit 53edefaddd4de4f2eba90033fda3e9b61d2c3c95
Author: Mason Remy <masonr@microsoft.com>
Date:   Fri May 27 21:14:50 2022 +0000

    Merged PR 2574: Support binding multiple indices to a processor handle

    Support binding multiple indices to a processor handle

    - This creates a mapping of the processor handle to the index iterations
      based on the ordering of the indices in the tuple

commit 6cf6faf95f72c7df3bf6acf39a29bb2591275781
Author: Chuck Jacobs <cjacobs@microsoft.com>
Date:   Fri May 27 19:55:20 2022 +0000

    Merged PR 2611: Fix issue when splitting indices by factors that don't divide evenly

    This PR fixes an issue when splitting by a factor that doesn't evenly divide the parent index's range. E.g., if `i` has a range of `[0, 320)`, then `ii = split(i, 128)` would end up with `ii` having a range of `192` instead of `128`.

commit 8c1a2da2e83e92fa07dd45c6d734cca1ab678f74
Author: Ritwik Das <ritdas@microsoft.com>
Date:   Fri May 27 16:09:39 2022 +0000

    Merged PR 2612: Add missing psutil dependency

    - Add missing psutil dependency
    - Remove private branch from benchmarks

commit 3e4a765acb1ab2905e57e6a37ee9e2448faaa870
Author: Ritwik Das <ritdas@microsoft.com>
Date:   Fri May 27 07:17:14 2022 +0000

    Merged PR 2608: Caching fixes and benchmarking optimizations

    - Explore k_split independently of outer tile dims, allows for arbitrary k splits
    - Fix for workPerThread < 1 (from Mason), which was exposed since the benchmark now explores k-split of size 1, 2, 4, etc. and this causes small active blocks for caching, and when work per thread becomes less than 1 the compiler crashes during package.build.

commit 11810900f837a261d97bb7589620a8fe7e82b70a
Author: Lisa Ong <onglisa@microsoft.com>
Date:   Fri May 27 01:29:45 2022 +0000

    Merged PR 2610: Opportunistically add more targets used in CI machines and update Model.md

    * Renamed some fields to add units
    * Added some Intel Xeon models as we encounter them
    * Updated some cache sizes

commit e6d31889676e69d9f884da9e543b295b1bfc7aed
Author: Denny Sun <dennys@microsoft.com>
Date:   Thu May 26 19:47:02 2022 +0000

    Merged PR 2606: Parameterize Array.sub_array

    `

            P0, P1 = create_parameters()
            arr = Array(role=Array.Role.INPUT_OUTPUT, element_type=ScalarType.float32, shape=(256, 256))
            arr0 = arr.sub_array(offsets=(0, 0), shape=(P0, P1))
            package.add(nest, args=(arr0, ),  parameters={P0: 128, P1: 128})
    `

    Related work items: #3707

commit cd39c8d4ead0392c7be87a059a2df70e6cf373a4
Author: Lisa Ong <onglisa@microsoft.com>
Date:   Thu May 26 09:13:30 2022 +0000

    Merged PR 2609: [build] peg protobuf to 3.20.1 due to incompatibilities with latest version

    Even though we peg to onnx==1.9.0, onnx requires protobuf >= 3.20.1 which pulls an incompatible version of protobuf (4.x).

commit ee0ad728c60353a3e8562d428dc1f6d9355cffa2
Author: Lisa Ong <onglisa@microsoft.com>
Date:   Wed May 25 08:08:31 2022 +0000

    Merged PR 2576: [doc] MFMA thread assignment visualizations for AMD

    Some helper visualizations for MFMA:
    * 2x2x16
    * 4x4x32

commit 90edd8ad70675bfb10bf448e0919f18a95b8453f
Author: Lisa Ong <onglisa@microsoft.com>
Date:   Wed May 25 07:12:07 2022 +0000

    Merged PR 2601: [ci] CUDA pipeline and buddy build

    * Container for CUDA self-hosted Azure devops agent
    * Initial buddy build pipeline (similar to ROCm)
    * Replaces references to Dockerhub with Azure Container Registry for compliance purposes

commit 0c2d6416bb1bf96e184b43289c55cf01522fa05b
Author: Lisa Ong <onglisa@microsoft.com>
Date:   Wed May 25 06:25:53 2022 +0000

    Merged PR 2603: Add CUDA pipeline host to known targets

    Note that the CPU frequency is conflicting, I went with cpuinfo and dmesg.

    References:

    ```
    > python -m cpuinfo

    Python Version: 3.8.10.final.0 (64 bit)
    Cpuinfo Version: 8.0.0
    Vendor ID Raw: AuthenticAMD
    Hardware Raw:
    Brand Raw: AMD EPYC 7V12 64-Core Processor
    Hz Advertised Friendly: 3.3049 GHz
    Hz Actual Friendly: 3.3049 GHz
    Hz Advertised: (3304919000, 0)
    Hz Actual: (3304919000, 0)
    Arch: X86_64
    Bits: 64
    Count: 128
    Arch String Raw: x86_64
    L1 Data Cache Size: 2 MiB
    L1 Instruction Cache Size: 2 MiB
    L2 Cache Size: 32 MiB
    L2 Cache Line Size: 512
    L2 Cache Associativity: 6
    L3 Cache Size: 524288
    Stepping:
    Model: 49
    Family: 23
    Processor Type:
    Flags: 3dnowext, 3dnowprefetch, abm, adx, aes, aperfmperf, apic, arat, avic, avx, avx2, bmi1, bmi2, bpext, cat_l3, cdp_l3, clflush, clflushopt, clwb, clzero, cmov, cmp_legacy, constant_tsc, cpb, cpuid, cqm, cqm_llc, cqm_mbm_local, cqm_mbm_total, cqm_occup_llc, cr8_legacy, cx16, cx8, dbx, de, decodeassists, extapic, extd_apicid, f16c, flushbyasid, fma, fpu, fsgsbase, fxsr, fxsr_opt, ht, hw_pstate, ibpb, ibrs, ibs, irperf, lahf_lm, lbrv, lm, mba, mca, mce, misalignsse, mmx, mmxext, monitor, movbe, msr, mtrr, mwaitx, nonstop_tsc, nopl, npt, nrip_save, nx, osvw, osxsave, overflow_recov, pae, pat, pausefilter, pci_l2i, pclmulqdq, pdpe1gb, perfctr_core, perfctr_llc, perfctr_nb, pfthreshold, pge, pni, popcnt, pqe, pqm, pse, pse36, rdpid, rdrand, rdrnd, rdseed, rdt_a, rdtscp, rep_good, sep, sev, sha, sha_ni, skinit, smap, smca, sme, smep, ssbd, sse, sse2, sse4_1, sse4_2, sse4a, ssse3, stibp, succor, svm, svm_lock, syscall, tce, topoext, tsc, tsc_scale, umip, v_vmsave_vmload, vgif, vmcb_clean, vme, vmmcall, wbnoinvd, wdt, xgetbv1, xsave, xsavec, xsaveerptr, xsaveopt, xsaves
    ```

    ```
    > dmesg | grep MHz
    [    0.000000] tsc: Detected 2450.083 MHz processor
    [    7.731766] hpet0: 3 comparators, 32-bit 14.318180 MHz counter
    [    8.979712] tsc: Refined TSC clocksource calibration: 2449.961 MHz
    ```

    ```
    > lscpu

    Architecture:                    x86_64
    CPU op-mode(s):                  32-bit, 64-bit
    Byte Order:                      Little Endian
    Address sizes:                   43 bits physical, 48 bits virtual
    CPU(s):                          128
    On-line CPU(s) list:             0-127
    Thread(s) per core:              2
    Core(s) per socket:              64
    Socket(s):                       1
    NUMA node(s):                    1
    Vendor ID:                       AuthenticAMD
    CPU family:                      23
    Model:                           49
    Model name:                      AMD EPYC 7V12 64-Core Processor
    Stepping:                        0
    Frequency boost:                 enabled
    CPU MHz:                         1497.558
    CPU max MHz:                     2450.0000
    CPU min MHz:                     1500.0000
    BogoMIPS:                        4900.16
    Virtualization:                  AMD-V
    L1d cache:                       2 MiB
    L1i cache:                       2 MiB
    L2 cache:                        32 MiB
    L3 cache:                        2...

commit d97008bfa45e1acbc2a37efee640bd15c3dfb8b4
Author: Ritwik Das <ritdas@microsoft.com>
Date:   Wed May 25 05:47:07 2022 +0000

    Merged PR 2602: Add rocwmma plumbing in tensorize

    - Add rocwmma plumbing in tensorize
    - Cannot use this flag until the 5.2 ROCm release which natively supports rocWmma.

    Related work items: #3672

commit 426d382e6f2441fe40b29748895a1eba2cb2677d
Author: Ritwik Das <ritdas@microsoft.com>
Date:   Wed May 25 03:52:48 2022 +0000

    Merged PR 2570: Enhancements to the gpu benchmark tool

    - Add multiprocess package builders and runners
    - Support for running on different GPU devices
    - Add clock speed determinism
    - add composable_kernel benchmarks
    - add cutlass benchmarks
    - add cublas and rocblas benchmarks
    - Add Cosmos DB result upload capability

    Related work items: #3683, #3700, #3705, #3685

commit 4454f6455b1324b1a97706604f9051cc9076f97b
Author: Mason Remy <masonr@microsoft.com>
Date:   Wed May 25 01:23:34 2022 +0000

    Merged PR 2598: Fix mfma enum name typo

    Fix mfma enum name typo

commit aaeb8d1883ce24873fd614efa9cc835383576f64
Author: Kern Handa <kerha@microsoft.com>
Date:   Tue May 24 07:29:17 2022 +0000

    Merged PR 2595: [nfc] Renames smoke_test.py -> smoke_tests.py

    [nfc] Renames smoke_test.py -> smoke_tests.py

commit fa7e10bcfd7f7424c976a7decaaaa1569d818525
Author: Lisa Ong <onglisa@microsoft.com>
Date:   Tue May 24 04:51:43 2022 +0000

    Merged PR 2593: [docs] [release] bump docs version to 1.2.5 in preparation for release

    bump docs version to 1.2.5 in preparation for release